from django import forms
from .models import installbase
from bootstrap_datepicker_plus import DatePickerInput


RACK = (
    ('Blank', 'Blank'),
    ('타장비 1U', '타장비 1U'),
    ('타장비 2U', '타장비 2U'),
    ('A800', 'A800'),
    ('A700', 'A700'),
    ('A400', 'A400'),
    ('AFF8080', 'AFF8080'),
    ('AFF8060', 'AFF8060'),
    ('AFF8040', 'AFF8040'),
    ('AFF8020', 'AFF8020'),
    ('FAS9000', 'FAS9000'),
    ('FAS8700', 'FAS8700'),
    ('FAS8300', 'FAS8300'),
    ('FAS8200', 'FAS8200'),
    ('FAS8080', 'FAS8080'),
    ('FAS8060', 'FAS8060'),
    ('FAS8040', 'FAS8040'),
    ('FAS8020', 'FAS8020'),
    ('FAS3200', 'FAS3200'),
    ('FAS2700', 'FAS2700'),
    ('FAS2600', 'FAS2600'),
    ('FAS2554', 'FAS2554'),
    ('FAS2552', 'FAS2552'),
    ('FAS2240-4', 'FAS2240-4'),
    ('FAS2240-2', 'FAS2240-2'),
    ('DS2246', 'DS2246'),
    ('DS224C', 'DS224C'),
    ('DS212C', 'DS212C'),
    ('DS460C', 'DS460C'),
    ('DS4243', 'DS4243'),
    ('DS4246', 'DS4246'),
    ('MDS SAN Switch', 'MDS SAN Switch'),
    ('ATTO Bridge', 'ATTO Bridge'),
    ('ClusterSwitch', 'ClusterSwitch'),
    ('ManagementSwitch', 'ManagementSwitch'),
    ('NULL', 'NULL'),
)

RACK_TOP1= (
    ('Blank', 'Blank'),
    ('타장비 1U', '타장비 1U'),
    ('타장비 2U', '타장비 2U'),
    ('A800', 'A800'),
    ('A400', 'A400'),
    ('AFF8080', 'AFF8080'),
    ('AFF8060', 'AFF8060'),
    ('AFF8040', 'AFF8040'),
    ('AFF8020', 'AFF8020'),
    ('FAS8700', 'FAS8700'),
    ('FAS8300', 'FAS8300'),
    ('FAS8200', 'FAS8200'),
    ('FAS8080', 'FAS8080'),
    ('FAS8060', 'FAS8060'),
    ('FAS8040', 'FAS8040'),
    ('FAS8020', 'FAS8020'),
    ('FAS3200', 'FAS3200'),
    ('FAS2700', 'FAS2700'),
    ('FAS2600', 'FAS2600'),
    ('FAS2554', 'FAS2554'),
    ('FAS2552', 'FAS2552'),
    ('FAS2240-4', 'FAS2240-4'),
    ('FAS2240-2', 'FAS2240-2'),
    ('DS2246', 'DS2246'),
    ('DS224C', 'DS224C'),
    ('DS212C', 'DS212C'),
    ('DS460C', 'DS460C'),
    ('DS4243', 'DS4243'),
    ('DS4246', 'DS4246'),
    ('MDS SAN Switch', 'MDS SAN Switch'),
    ('ATTO Bridge', 'ATTO Bridge'),
    ('ClusterSwitch', 'ClusterSwitch'),
    ('ManagementSwitch', 'ManagementSwitch'),
    ('NULL', 'NULL'),
)

RACK_TOP2= (
    ('Blank', 'Blank'),
    ('타장비 1U', '타장비 1U'),
    ('타장비 2U', '타장비 2U'),
    ('A800', 'A800'),
    ('A400', 'A400'),
    ('AFF8020', 'AFF8020'),
    ('FAS8700', 'FAS8700'),
    ('FAS8300', 'FAS8300'),
    ('FAS8200', 'FAS8200'),
    ('FAS3200', 'FAS3200'),
    ('FAS2700', 'FAS2700'),
    ('FAS2600', 'FAS2600'),
    ('FAS2554', 'FAS2554'),
    ('FAS2552', 'FAS2552'),
    ('FAS2240-4', 'FAS2240-4'),
    ('FAS2240-2', 'FAS2240-2'),
    ('DS2246', 'DS2246'),
    ('DS224C', 'DS224C'),
    ('DS212C', 'DS212C'),
    ('DS460C', 'DS460C'),
    ('DS4243', 'DS4243'),
    ('DS4246', 'DS4246'),
    ('MDS SAN Switch', 'MDS SAN Switch'),
    ('ATTO Bridge', 'ATTO Bridge'),
    ('ClusterSwitch', 'ClusterSwitch'),
    ('ManagementSwitch', 'ManagementSwitch'),
    ('NULL', 'NULL'),
)

RACK_TOP3= (
    ('Blank', 'Blank'),
    ('타장비 1U', '타장비 1U'),
    ('타장비 2U', '타장비 2U'),
    ('AFF8020', 'AFF8020'),
    ('FAS8200', 'FAS8200'),
    ('FAS2700', 'FAS2700'),
    ('FAS2600', 'FAS2600'),
    ('FAS2552', 'FAS2552'),
    ('FAS2240-2', 'FAS2240-2'),
    ('DS2246', 'DS2246'),
    ('DS224C', 'DS224C'),
    ('DS212C', 'DS212C'),
    ('MDS SAN Switch', 'MDS SAN Switch'),
    ('ATTO Bridge', 'ATTO Bridge'),
    ('ClusterSwitch', 'ClusterSwitch'),
    ('ManagementSwitch', 'ManagementSwitch'),
    ('NULL', 'NULL'),
)

RACK_TOP4= (
    ('Blank', 'Blank'),
    ('타장비 1U', '타장비 1U'),
    ('타장비 2U', '타장비 2U'),
    ('FAS2700', 'FAS2700'),
    ('FAS2600', 'FAS2600'),
    ('FAS2552', 'FAS2552'),
    ('FAS2240-2', 'FAS2240-2'),
    ('DS2246', 'DS2246'),
    ('DS224C', 'DS224C'),
    ('DS212C', 'DS212C'),
    ('MDS SAN Switch', 'MDS SAN Switch'),
    ('ATTO Bridge', 'ATTO Bridge'),
    ('ClusterSwitch', 'ClusterSwitch'),
    ('ManagementSwitch', 'ManagementSwitch'),
    ('NULL', 'NULL'),
)

RACK_TOP5= (
    ('Blank', 'Blank'),
    ('타장비 1U', '타장비 1U'),
    ('MDS SAN Switch', 'MDS SAN Switch'),
    ('ATTO Bridge', 'ATTO Bridge'),
    ('ClusterSwitch', 'ClusterSwitch'),
    ('ManagementSwitch', 'ManagementSwitch'),
    ('NULL', 'NULL'),
)

class InstallBaseform(forms.ModelForm):
    class Meta:
        model = installbase
        fields = ['production', 'customer', 'installedat', 'project_name', 'model', 'osversion', 'serialnumber', 'activeiq','hostname', 'licensed', 'ipslist', 'shelfmodel', 'disk', 'diskmodel', 'shelfemptyslot', 'slotinfo', 'installedate','warrantytype', 'warrantydate', 'engineername', 'customer_manager', 'controllereoa', 'controllereos', 'sanswitch', 'sanswitchserial', 'sanswitchmodel', 'sanswitchhostname', 'sanswitchport', 'sanswitchportlicense', 'sanswitchipaddress', 'addlist', 'upload_files', 'filename']
        widgets = {
            'licensed': forms.CheckboxSelectMultiple(),
            'production': forms.RadioSelect(choices=((True, '운영'), (False, '백업'))),
            'customer': forms.TextInput(attrs={'class': 'form-control'}),
            'installedat': forms.Textarea(attrs={'class': 'form-control', 'rows': 2}),
            'project_name': forms.TextInput(attrs={'class': 'form-control'}),
            'model': forms.TextInput(attrs={'class': 'form-control'}),
            'osversion': forms.TextInput(attrs={'class': 'form-control'}),
            'serialnumber': forms.Textarea(attrs={'class': 'form-control', 'rows': 3}),
            'hostname': forms.Textarea(attrs={'class': 'form-control', 'rows': 2}),
            'ipslist': forms.Textarea(attrs={'class': 'form-control', 'rows': 8}),
            'shelfmodel': forms.Textarea(attrs={'class': 'form-control', 'rows': 2}),
            'disk': forms.Textarea(attrs={'class': 'form-control', 'rows': 2}),
            'diskmodel': forms.Textarea(attrs={'class': 'form-control', 'rows': 4}),
            'shelfemptyslot': forms.Textarea(attrs={'class': 'form-control', 'rows': 2}),
            'slotinfo': forms.Textarea(attrs={'class': 'form-control', 'rows': 2}),
            'sanswitch': forms.Select(choices=((0, '없음'), (1 , '있음'))),
            'sanswitchserial': forms.Textarea(attrs={'class': 'form-control', 'rows': 2}),
            'sanswitchmodel': forms.Textarea(attrs={'class': 'form-control', 'rows': 2}),
            'sanswitchhostname': forms.Textarea(attrs={'class': 'form-control', 'rows': 2}),
            'sanswitchport': forms.TextInput(attrs={'class': 'form-control'}),
            'sanswitchportlicense': forms.TextInput(attrs={'class': 'form-control'}),
            'sanswitchipaddress': forms.Textarea(attrs={'class': 'form-control', 'rows': 2}),
            'engineername': forms.TextInput(attrs={'class': 'form-control'}),
            'addlist': forms.Textarea(attrs={'class': 'form-control', 'rows': 4}),
            'installedate': DatePickerInput(format='%m/%d/%Y'),
            'warrantytype': forms.Select(choices=(('무상', '무상'), ('유상' , '유상'), ('타부서', '타부서'))),
            'warrantydate': DatePickerInput(format='%m/%d/%Y'),
            'controllereoa': DatePickerInput(format='%m/%d/%Y'),
            'controllereos': DatePickerInput(format='%m/%d/%Y'),
            'upload_files': forms.ClearableFileInput(),
            'filename': forms.HiddenInput(attrs={'class': 'form-control'}),
	    'customer_manager': forms.TextInput(attrs={'class': 'form-control'}),
	    'activeiq': forms.RadioSelect(choices=((True, 'Enable'), (False, 'Disable'))),
            'unit1_1': forms.Select(choices=RACK, attrs={'onchange': "rack();", 'name': 1}),
            'unit1_2': forms.Select(choices=RACK),
            'unit1_3': forms.Select(choices=RACK),
            'unit1_4': forms.Select(choices=RACK),
            'unit1_5': forms.Select(choices=RACK),
            'unit1_6': forms.Select(choices=RACK),
            'unit1_7': forms.Select(choices=RACK),
            'unit1_8': forms.Select(choices=RACK),
            'unit1_9': forms.Select(choices=RACK),
            'unit1_10': forms.Select(choices=RACK),
            'unit1_11': forms.Select(choices=RACK),
            'unit1_12': forms.Select(choices=RACK),
            'unit1_13': forms.Select(choices=RACK),
            'unit1_14': forms.Select(choices=RACK),
            'unit1_15': forms.Select(choices=RACK),
            'unit1_16': forms.Select(choices=RACK),
            'unit1_17': forms.Select(choices=RACK),
            'unit1_18': forms.Select(choices=RACK),
            'unit1_19': forms.Select(choices=RACK),
            'unit1_20': forms.Select(choices=RACK),
            'unit1_21': forms.Select(choices=RACK),
            'unit1_22': forms.Select(choices=RACK),
            'unit1_23': forms.Select(choices=RACK),
            'unit1_24': forms.Select(choices=RACK),
            'unit1_25': forms.Select(choices=RACK),
            'unit1_26': forms.Select(choices=RACK),
            'unit1_27': forms.Select(choices=RACK),
            'unit1_28': forms.Select(choices=RACK),
            'unit1_29': forms.Select(choices=RACK),
            'unit1_30': forms.Select(choices=RACK),
            'unit1_31': forms.Select(choices=RACK),
            'unit1_32': forms.Select(choices=RACK),
            'unit1_33': forms.Select(choices=RACK),
            'unit1_34': forms.Select(choices=RACK),
            'unit1_35': forms.Select(choices=RACK),
            'unit1_36': forms.Select(choices=RACK_TOP1),
            'unit1_37': forms.Select(choices=RACK_TOP1),
            'unit1_38': forms.Select(choices=RACK_TOP2),
            'unit1_39': forms.Select(choices=RACK_TOP2),
            'unit1_40': forms.Select(choices=RACK_TOP3),
            'unit1_41': forms.Select(choices=RACK_TOP4),
            'unit1_42': forms.Select(choices=RACK_TOP5),
            'unit2_1': forms.Select(choices=RACK),
            'unit2_2': forms.Select(choices=RACK),
            'unit2_3': forms.Select(choices=RACK),
            'unit2_4': forms.Select(choices=RACK),
            'unit2_5': forms.Select(choices=RACK),
            'unit2_6': forms.Select(choices=RACK),
            'unit2_7': forms.Select(choices=RACK),
            'unit2_8': forms.Select(choices=RACK),
            'unit2_9': forms.Select(choices=RACK),
            'unit2_10': forms.Select(choices=RACK),
            'unit2_11': forms.Select(choices=RACK),
            'unit2_12': forms.Select(choices=RACK),
            'unit2_13': forms.Select(choices=RACK),
            'unit2_14': forms.Select(choices=RACK),
            'unit2_15': forms.Select(choices=RACK),
            'unit2_16': forms.Select(choices=RACK),
            'unit2_17': forms.Select(choices=RACK),
            'unit2_18': forms.Select(choices=RACK),
            'unit2_19': forms.Select(choices=RACK),
            'unit2_20': forms.Select(choices=RACK),
            'unit2_21': forms.Select(choices=RACK),
            'unit2_22': forms.Select(choices=RACK),
            'unit2_23': forms.Select(choices=RACK),
            'unit2_24': forms.Select(choices=RACK),
            'unit2_25': forms.Select(choices=RACK),
            'unit2_26': forms.Select(choices=RACK),
            'unit2_27': forms.Select(choices=RACK),
            'unit2_28': forms.Select(choices=RACK),
            'unit2_29': forms.Select(choices=RACK),
            'unit2_30': forms.Select(choices=RACK),
            'unit2_31': forms.Select(choices=RACK),
            'unit2_32': forms.Select(choices=RACK),
            'unit2_33': forms.Select(choices=RACK),
            'unit2_34': forms.Select(choices=RACK),
            'unit2_35': forms.Select(choices=RACK),
            'unit2_36': forms.Select(choices=RACK_TOP1),
            'unit2_37': forms.Select(choices=RACK_TOP1),
            'unit2_38': forms.Select(choices=RACK_TOP2),
            'unit2_39': forms.Select(choices=RACK_TOP2),
            'unit2_40': forms.Select(choices=RACK_TOP3),
            'unit2_41': forms.Select(choices=RACK_TOP4),
            'unit2_42': forms.Select(choices=RACK_TOP5),
            'unit3_1': forms.Select(choices=RACK),
            'unit3_2': forms.Select(choices=RACK),
            'unit3_3': forms.Select(choices=RACK),
            'unit3_4': forms.Select(choices=RACK),
            'unit3_5': forms.Select(choices=RACK),
            'unit3_6': forms.Select(choices=RACK),
            'unit3_7': forms.Select(choices=RACK),
            'unit3_8': forms.Select(choices=RACK),
            'unit3_9': forms.Select(choices=RACK),
            'unit3_10': forms.Select(choices=RACK),
            'unit3_11': forms.Select(choices=RACK),
            'unit3_12': forms.Select(choices=RACK),
            'unit3_13': forms.Select(choices=RACK),
            'unit3_14': forms.Select(choices=RACK),
            'unit3_15': forms.Select(choices=RACK),
            'unit3_16': forms.Select(choices=RACK),
            'unit3_17': forms.Select(choices=RACK),
            'unit3_18': forms.Select(choices=RACK),
            'unit3_19': forms.Select(choices=RACK),
            'unit3_20': forms.Select(choices=RACK),
            'unit3_21': forms.Select(choices=RACK),
            'unit3_22': forms.Select(choices=RACK),
            'unit3_23': forms.Select(choices=RACK),
            'unit3_24': forms.Select(choices=RACK),
            'unit3_25': forms.Select(choices=RACK),
            'unit3_26': forms.Select(choices=RACK),
            'unit3_27': forms.Select(choices=RACK),
            'unit3_28': forms.Select(choices=RACK),
            'unit3_29': forms.Select(choices=RACK),
            'unit3_30': forms.Select(choices=RACK),
            'unit3_31': forms.Select(choices=RACK),
            'unit3_32': forms.Select(choices=RACK),
            'unit3_33': forms.Select(choices=RACK),
            'unit3_34': forms.Select(choices=RACK),
            'unit3_35': forms.Select(choices=RACK),
            'unit3_36': forms.Select(choices=RACK_TOP1),
            'unit3_37': forms.Select(choices=RACK_TOP1),
            'unit3_38': forms.Select(choices=RACK_TOP2),
            'unit3_39': forms.Select(choices=RACK_TOP2),
            'unit3_40': forms.Select(choices=RACK_TOP3),
            'unit3_41': forms.Select(choices=RACK_TOP4),
            'unit3_42': forms.Select(choices=RACK_TOP5),
            'unit4_1': forms.Select(choices=RACK),
            'unit4_2': forms.Select(choices=RACK),
            'unit4_3': forms.Select(choices=RACK),
            'unit4_4': forms.Select(choices=RACK),
            'unit4_5': forms.Select(choices=RACK),
            'unit4_6': forms.Select(choices=RACK),
            'unit4_7': forms.Select(choices=RACK),
            'unit4_8': forms.Select(choices=RACK),
            'unit4_9': forms.Select(choices=RACK),
            'unit4_10': forms.Select(choices=RACK),
            'unit4_11': forms.Select(choices=RACK),
            'unit4_12': forms.Select(choices=RACK),
            'unit4_13': forms.Select(choices=RACK),
            'unit4_14': forms.Select(choices=RACK),
            'unit4_15': forms.Select(choices=RACK),
            'unit4_16': forms.Select(choices=RACK),
            'unit4_17': forms.Select(choices=RACK),
            'unit4_18': forms.Select(choices=RACK),
            'unit4_19': forms.Select(choices=RACK),
            'unit4_20': forms.Select(choices=RACK),
            'unit4_21': forms.Select(choices=RACK),
            'unit4_22': forms.Select(choices=RACK),
            'unit4_23': forms.Select(choices=RACK),
            'unit4_24': forms.Select(choices=RACK),
            'unit4_25': forms.Select(choices=RACK),
            'unit4_26': forms.Select(choices=RACK),
            'unit4_27': forms.Select(choices=RACK),
            'unit4_28': forms.Select(choices=RACK),
            'unit4_29': forms.Select(choices=RACK),
            'unit4_30': forms.Select(choices=RACK),
            'unit4_31': forms.Select(choices=RACK),
            'unit4_32': forms.Select(choices=RACK),
            'unit4_33': forms.Select(choices=RACK),
            'unit4_34': forms.Select(choices=RACK),
            'unit4_35': forms.Select(choices=RACK),
            'unit4_36': forms.Select(choices=RACK_TOP1),
            'unit4_37': forms.Select(choices=RACK_TOP1),
            'unit4_38': forms.Select(choices=RACK_TOP2),
            'unit4_39': forms.Select(choices=RACK_TOP2),
            'unit4_40': forms.Select(choices=RACK_TOP3),
            'unit4_41': forms.Select(choices=RACK_TOP4),
            'unit4_42': forms.Select(choices=RACK_TOP5),
        }
        labels = {
            'production': '운영/백업',
            'customer': '고객사',
            'installedat': '설치 위치',
            'project_name': '프로젝트명',
            'model': '스토리지 모델',
            'osversion': 'OS버전',
            'serialnumber': '시리얼',
            'hostname': 'HOSTNAME',
            'ipslist': 'IP 리스트',
            'shelfmodel': 'Shelf 모델',
            'disk': 'Disk 수량',
            'diskmodel': 'Disk 모델',
            'shelfemptyslot': 'Shelf 빈슬롯 정보',
            'slotinfo': '컨트롤러 슬롯 정보',
            'engineername': '담당 엔지니어',
            'addlist': '증설 이력',
            'installedate': '초기설치일',
            'warrantytype': '워런티 타입',
            'warrantydate': '워런티 종료일',
            'controllereoa': '컨트롤러 EOA',
            'controllereos': '컨트롤러 EOS',
            'sanswitch': 'SAN Switch',
            'sanswitchserial': 'SAN Switch Serial',
            'sanswitchmodel': 'SAN Switch Model',
            'sanswitchhostname': 'SAN Switch HostName',
            'sanswitchport': 'SAN Switch 잔여 포트',
            'sanswitchportlicense': 'SAN Switch 포트 라이센스 수량',
            'sanswitchipaddress': 'SAN Switch IP Address',
            'upload_files': '첨부파일',
	    'customer_manager': '고객 담당자',
	    'activeiq': 'NetApp Active IQ',
        }

class Rackform(forms.ModelForm):
    class Meta:
        model = installbase
        fields = ['rack1','rack2','rack3','rack4','unit1_42', 'unit1_41', 'unit1_40', 'unit1_39', 'unit1_38', 'unit1_37', 'unit1_36', 'unit1_35', 'unit1_34', 'unit1_33', 'unit1_32', 'unit1_31', 'unit1_30', 'unit1_29', 'unit1_28', 'unit1_27', 'unit1_26', 'unit1_25', 'unit1_24', 'unit1_23', 'unit1_22', 'unit1_21', 'unit1_20', 'unit1_19', 'unit1_18', 'unit1_17', 'unit1_16', 'unit1_15', 'unit1_14', 'unit1_13', 'unit1_12', 'unit1_11', 'unit1_10', 'unit1_9', 'unit1_8', 'unit1_7', 'unit1_6', 'unit1_5', 'unit1_4', 'unit1_3', 'unit1_2', 'unit1_1','unit2_42', 'unit2_41', 'unit2_40', 'unit2_39', 'unit2_38', 'unit2_37', 'unit2_36', 'unit2_35', 'unit2_34', 'unit2_33', 'unit2_32', 'unit2_31', 'unit2_30', 'unit2_29', 'unit2_28', 'unit2_27', 'unit2_26', 'unit2_25', 'unit2_24', 'unit2_23', 'unit2_22', 'unit2_21', 'unit2_20', 'unit2_19', 'unit2_18', 'unit2_17', 'unit2_16', 'unit2_15', 'unit2_14', 'unit2_13', 'unit2_12', 'unit2_11', 'unit2_10', 'unit2_9', 'unit2_8', 'unit2_7', 'unit2_6', 'unit2_5', 'unit2_4', 'unit2_3', 'unit2_2', 'unit2_1','unit3_42', 'unit3_41', 'unit3_40', 'unit3_39', 'unit3_38', 'unit3_37', 'unit3_36', 'unit3_35', 'unit3_34', 'unit3_33', 'unit3_32', 'unit3_31', 'unit3_30', 'unit3_29', 'unit3_28', 'unit3_27', 'unit3_26', 'unit3_25', 'unit3_24', 'unit3_23', 'unit3_22', 'unit3_21', 'unit3_20', 'unit3_19', 'unit3_18', 'unit3_17', 'unit3_16', 'unit3_15', 'unit3_14', 'unit3_13', 'unit3_12', 'unit3_11', 'unit3_10', 'unit3_9', 'unit3_8', 'unit3_7', 'unit3_6', 'unit3_5', 'unit3_4', 'unit3_3', 'unit3_2', 'unit3_1','unit4_42', 'unit4_41', 'unit4_40', 'unit4_39', 'unit4_38', 'unit4_37', 'unit4_36', 'unit4_35', 'unit4_34', 'unit4_33', 'unit4_32', 'unit4_31', 'unit4_30', 'unit4_29', 'unit4_28', 'unit4_27', 'unit4_26', 'unit4_25', 'unit4_24', 'unit4_23', 'unit4_22', 'unit4_21', 'unit4_20', 'unit4_19', 'unit4_18', 'unit4_17', 'unit4_16', 'unit4_15', 'unit4_14', 'unit4_13', 'unit4_12', 'unit4_11', 'unit4_10', 'unit4_9', 'unit4_8', 'unit4_7', 'unit4_6', 'unit4_5', 'unit4_4', 'unit4_3', 'unit4_2', 'unit4_1', 'unit1_1_description' , 'unit1_2_description' , 'unit1_3_description' , 'unit1_4_description' , 'unit1_5_description' , 'unit1_6_description' , 'unit1_7_description' , 'unit1_8_description' , 'unit1_9_description' , 'unit1_10_description' , 'unit1_11_description' , 'unit1_12_description' , 'unit1_13_description' , 'unit1_14_description' , 'unit1_15_description' , 'unit1_16_description' , 'unit1_17_description' , 'unit1_18_description' , 'unit1_19_description' , 'unit1_20_description' , 'unit1_21_description' , 'unit1_22_description' , 'unit1_23_description' , 'unit1_24_description' , 'unit1_25_description' , 'unit1_26_description' , 'unit1_27_description' , 'unit1_28_description' , 'unit1_29_description' , 'unit1_30_description' , 'unit1_31_description' , 'unit1_32_description' , 'unit1_33_description' , 'unit1_34_description' , 'unit1_35_description' , 'unit1_36_description' , 'unit1_37_description' , 'unit1_38_description' , 'unit1_39_description' , 'unit1_40_description' , 'unit1_41_description' , 'unit1_42_description', 'unit2_1_description' , 'unit2_2_description' , 'unit2_3_description' , 'unit2_4_description' , 'unit2_5_description' , 'unit2_6_description' , 'unit2_7_description' , 'unit2_8_description' , 'unit2_9_description' , 'unit2_10_description' , 'unit2_11_description' , 'unit2_12_description' , 'unit2_13_description' , 'unit2_14_description' , 'unit2_15_description' , 'unit2_16_description' , 'unit2_17_description' , 'unit2_18_description' , 'unit2_19_description' , 'unit2_20_description' , 'unit2_21_description' , 'unit2_22_description' , 'unit2_23_description' , 'unit2_24_description' , 'unit2_25_description' , 'unit2_26_description' , 'unit2_27_description' , 'unit2_28_description' , 'unit2_29_description' , 'unit2_30_description' , 'unit2_31_description' , 'unit2_32_description' , 'unit2_33_description' , 'unit2_34_description' , 'unit2_35_description' , 'unit2_36_description' , 'unit2_37_description' , 'unit2_38_description' , 'unit2_39_description' , 'unit2_40_description' , 'unit2_41_description' , 'unit2_42_description', 'unit3_1_description' , 'unit3_2_description' , 'unit3_3_description' , 'unit3_4_description' , 'unit3_5_description' , 'unit3_6_description' , 'unit3_7_description' , 'unit3_8_description' , 'unit3_9_description' , 'unit3_10_description' , 'unit3_11_description' , 'unit3_12_description' , 'unit3_13_description' , 'unit3_14_description' , 'unit3_15_description' , 'unit3_16_description' , 'unit3_17_description' , 'unit3_18_description' , 'unit3_19_description' , 'unit3_20_description' , 'unit3_21_description' , 'unit3_22_description' , 'unit3_23_description' , 'unit3_24_description' , 'unit3_25_description' , 'unit3_26_description' , 'unit3_27_description' , 'unit3_28_description' , 'unit3_29_description' , 'unit3_30_description' , 'unit3_31_description' , 'unit3_32_description' , 'unit3_33_description' , 'unit3_34_description' , 'unit3_35_description' , 'unit3_36_description' , 'unit3_37_description' , 'unit3_38_description' , 'unit3_39_description' , 'unit3_40_description' , 'unit3_41_description' , 'unit3_42_description', 'unit4_1_description' , 'unit4_2_description' , 'unit4_3_description' , 'unit4_4_description' , 'unit4_5_description' , 'unit4_6_description' , 'unit4_7_description' , 'unit4_8_description' , 'unit4_9_description' , 'unit4_10_description' , 'unit4_11_description' , 'unit4_12_description' , 'unit4_13_description' , 'unit4_14_description' , 'unit4_15_description' , 'unit4_16_description' , 'unit4_17_description' , 'unit4_18_description' , 'unit4_19_description' , 'unit4_20_description' , 'unit4_21_description' , 'unit4_22_description' , 'unit4_23_description' , 'unit4_24_description' , 'unit4_25_description' , 'unit4_26_description' , 'unit4_27_description' , 'unit4_28_description' , 'unit4_29_description' , 'unit4_30_description' , 'unit4_31_description' , 'unit4_32_description' , 'unit4_33_description' , 'unit4_34_description' , 'unit4_35_description' , 'unit4_36_description' , 'unit4_37_description' , 'unit4_38_description' , 'unit4_39_description' , 'unit4_40_description' , 'unit4_41_description' , 'unit4_42_description']
        widgets = {
            'rack1': forms.TextInput(attrs={'class': 'form-control'}),
            'rack2': forms.TextInput(attrs={'class': 'form-control'}),
            'rack3': forms.TextInput(attrs={'class': 'form-control'}),
            'rack4': forms.TextInput(attrs={'class': 'form-control'}),
            'unit1_1': forms.Select(choices=RACK),
            'unit1_2': forms.Select(choices=RACK),
            'unit1_3': forms.Select(choices=RACK),
            'unit1_4': forms.Select(choices=RACK),
            'unit1_5': forms.Select(choices=RACK),
            'unit1_6': forms.Select(choices=RACK),
            'unit1_7': forms.Select(choices=RACK),
            'unit1_8': forms.Select(choices=RACK),
            'unit1_9': forms.Select(choices=RACK),
            'unit1_10': forms.Select(choices=RACK),
            'unit1_11': forms.Select(choices=RACK),
            'unit1_12': forms.Select(choices=RACK),
            'unit1_13': forms.Select(choices=RACK),
            'unit1_14': forms.Select(choices=RACK),
            'unit1_15': forms.Select(choices=RACK),
            'unit1_16': forms.Select(choices=RACK),
            'unit1_17': forms.Select(choices=RACK),
            'unit1_18': forms.Select(choices=RACK),
            'unit1_19': forms.Select(choices=RACK),
            'unit1_20': forms.Select(choices=RACK),
            'unit1_21': forms.Select(choices=RACK),
            'unit1_22': forms.Select(choices=RACK),
            'unit1_23': forms.Select(choices=RACK),
            'unit1_24': forms.Select(choices=RACK),
            'unit1_25': forms.Select(choices=RACK),
            'unit1_26': forms.Select(choices=RACK),
            'unit1_27': forms.Select(choices=RACK),
            'unit1_28': forms.Select(choices=RACK),
            'unit1_29': forms.Select(choices=RACK),
            'unit1_30': forms.Select(choices=RACK),
            'unit1_31': forms.Select(choices=RACK),
            'unit1_32': forms.Select(choices=RACK),
            'unit1_33': forms.Select(choices=RACK),
            'unit1_34': forms.Select(choices=RACK),
            'unit1_35': forms.Select(choices=RACK),
            'unit1_36': forms.Select(choices=RACK_TOP1),
            'unit1_37': forms.Select(choices=RACK_TOP1),
            'unit1_38': forms.Select(choices=RACK_TOP2),
            'unit1_39': forms.Select(choices=RACK_TOP2),
            'unit1_40': forms.Select(choices=RACK_TOP3),
            'unit1_41': forms.Select(choices=RACK_TOP4),
            'unit1_42': forms.Select(choices=RACK_TOP5),
            'unit2_1': forms.Select(choices=RACK),
            'unit2_2': forms.Select(choices=RACK),
            'unit2_3': forms.Select(choices=RACK),
            'unit2_4': forms.Select(choices=RACK),
            'unit2_5': forms.Select(choices=RACK),
            'unit2_6': forms.Select(choices=RACK),
            'unit2_7': forms.Select(choices=RACK),
            'unit2_8': forms.Select(choices=RACK),
            'unit2_9': forms.Select(choices=RACK),
            'unit2_10': forms.Select(choices=RACK),
            'unit2_11': forms.Select(choices=RACK),
            'unit2_12': forms.Select(choices=RACK),
            'unit2_13': forms.Select(choices=RACK),
            'unit2_14': forms.Select(choices=RACK),
            'unit2_15': forms.Select(choices=RACK),
            'unit2_16': forms.Select(choices=RACK),
            'unit2_17': forms.Select(choices=RACK),
            'unit2_18': forms.Select(choices=RACK),
            'unit2_19': forms.Select(choices=RACK),
            'unit2_20': forms.Select(choices=RACK),
            'unit2_21': forms.Select(choices=RACK),
            'unit2_22': forms.Select(choices=RACK),
            'unit2_23': forms.Select(choices=RACK),
            'unit2_24': forms.Select(choices=RACK),
            'unit2_25': forms.Select(choices=RACK),
            'unit2_26': forms.Select(choices=RACK),
            'unit2_27': forms.Select(choices=RACK),
            'unit2_28': forms.Select(choices=RACK),
            'unit2_29': forms.Select(choices=RACK),
            'unit2_30': forms.Select(choices=RACK),
            'unit2_31': forms.Select(choices=RACK),
            'unit2_32': forms.Select(choices=RACK),
            'unit2_33': forms.Select(choices=RACK),
            'unit2_34': forms.Select(choices=RACK),
            'unit2_35': forms.Select(choices=RACK),
            'unit2_36': forms.Select(choices=RACK_TOP1),
            'unit2_37': forms.Select(choices=RACK_TOP1),
            'unit2_38': forms.Select(choices=RACK_TOP2),
            'unit2_39': forms.Select(choices=RACK_TOP2),
            'unit2_40': forms.Select(choices=RACK_TOP3),
            'unit2_41': forms.Select(choices=RACK_TOP4),
            'unit2_42': forms.Select(choices=RACK_TOP5),
            'unit3_1': forms.Select(choices=RACK),
            'unit3_2': forms.Select(choices=RACK),
            'unit3_3': forms.Select(choices=RACK),
            'unit3_4': forms.Select(choices=RACK),
            'unit3_5': forms.Select(choices=RACK),
            'unit3_6': forms.Select(choices=RACK),
            'unit3_7': forms.Select(choices=RACK),
            'unit3_8': forms.Select(choices=RACK),
            'unit3_9': forms.Select(choices=RACK),
            'unit3_10': forms.Select(choices=RACK),
            'unit3_11': forms.Select(choices=RACK),
            'unit3_12': forms.Select(choices=RACK),
            'unit3_13': forms.Select(choices=RACK),
            'unit3_14': forms.Select(choices=RACK),
            'unit3_15': forms.Select(choices=RACK),
            'unit3_16': forms.Select(choices=RACK),
            'unit3_17': forms.Select(choices=RACK),
            'unit3_18': forms.Select(choices=RACK),
            'unit3_19': forms.Select(choices=RACK),
            'unit3_20': forms.Select(choices=RACK),
            'unit3_21': forms.Select(choices=RACK),
            'unit3_22': forms.Select(choices=RACK),
            'unit3_23': forms.Select(choices=RACK),
            'unit3_24': forms.Select(choices=RACK),
            'unit3_25': forms.Select(choices=RACK),
            'unit3_26': forms.Select(choices=RACK),
            'unit3_27': forms.Select(choices=RACK),
            'unit3_28': forms.Select(choices=RACK),
            'unit3_29': forms.Select(choices=RACK),
            'unit3_30': forms.Select(choices=RACK),
            'unit3_31': forms.Select(choices=RACK),
            'unit3_32': forms.Select(choices=RACK),
            'unit3_33': forms.Select(choices=RACK),
            'unit3_34': forms.Select(choices=RACK),
            'unit3_35': forms.Select(choices=RACK),
            'unit3_36': forms.Select(choices=RACK_TOP1),
            'unit3_37': forms.Select(choices=RACK_TOP1),
            'unit3_38': forms.Select(choices=RACK_TOP2),
            'unit3_39': forms.Select(choices=RACK_TOP2),
            'unit3_40': forms.Select(choices=RACK_TOP3),
            'unit3_41': forms.Select(choices=RACK_TOP4),
            'unit3_42': forms.Select(choices=RACK_TOP5),
            'unit4_1': forms.Select(choices=RACK),
            'unit4_2': forms.Select(choices=RACK),
            'unit4_3': forms.Select(choices=RACK),
            'unit4_4': forms.Select(choices=RACK),
            'unit4_5': forms.Select(choices=RACK),
            'unit4_6': forms.Select(choices=RACK),
            'unit4_7': forms.Select(choices=RACK),
            'unit4_8': forms.Select(choices=RACK),
            'unit4_9': forms.Select(choices=RACK),
            'unit4_10': forms.Select(choices=RACK),
            'unit4_11': forms.Select(choices=RACK),
            'unit4_12': forms.Select(choices=RACK),
            'unit4_13': forms.Select(choices=RACK),
            'unit4_14': forms.Select(choices=RACK),
            'unit4_15': forms.Select(choices=RACK),
            'unit4_16': forms.Select(choices=RACK),
            'unit4_17': forms.Select(choices=RACK),
            'unit4_18': forms.Select(choices=RACK),
            'unit4_19': forms.Select(choices=RACK),
            'unit4_20': forms.Select(choices=RACK),
            'unit4_21': forms.Select(choices=RACK),
            'unit4_22': forms.Select(choices=RACK),
            'unit4_23': forms.Select(choices=RACK),
            'unit4_24': forms.Select(choices=RACK),
            'unit4_25': forms.Select(choices=RACK),
            'unit4_26': forms.Select(choices=RACK),
            'unit4_27': forms.Select(choices=RACK),
            'unit4_28': forms.Select(choices=RACK),
            'unit4_29': forms.Select(choices=RACK),
            'unit4_30': forms.Select(choices=RACK),
            'unit4_31': forms.Select(choices=RACK),
            'unit4_32': forms.Select(choices=RACK),
            'unit4_33': forms.Select(choices=RACK),
            'unit4_34': forms.Select(choices=RACK),
            'unit4_35': forms.Select(choices=RACK),
            'unit4_36': forms.Select(choices=RACK_TOP1),
            'unit4_37': forms.Select(choices=RACK_TOP1),
            'unit4_38': forms.Select(choices=RACK_TOP2),
            'unit4_39': forms.Select(choices=RACK_TOP2),
            'unit4_40': forms.Select(choices=RACK_TOP3),
            'unit4_41': forms.Select(choices=RACK_TOP4),
            'unit4_42': forms.Select(choices=RACK_TOP5),
            'unit1_1_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit1_2_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit1_3_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit1_4_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit1_5_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit1_6_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit1_7_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit1_8_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit1_9_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit1_10_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit1_11_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit1_12_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit1_13_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit1_14_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit1_15_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit1_16_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit1_17_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit1_18_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit1_19_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit1_20_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit1_21_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit1_22_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit1_23_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit1_24_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit1_25_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit1_26_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit1_27_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit1_28_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit1_29_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit1_30_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit1_31_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit1_32_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit1_33_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit1_34_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit1_35_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit1_36_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit1_37_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit1_38_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit1_39_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit1_40_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit1_41_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit1_42_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit2_1_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit2_2_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit2_3_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit2_4_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit2_5_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit2_6_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit2_7_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit2_8_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit2_9_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit2_10_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit2_11_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit2_12_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit2_13_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit2_14_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit2_15_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit2_16_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit2_17_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit2_18_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit2_19_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit2_20_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit2_21_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit2_22_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit2_23_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit2_24_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit2_25_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit2_26_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit2_27_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit2_28_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit2_29_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit2_30_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit2_31_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit2_32_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit2_33_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit2_34_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit2_35_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit2_36_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit2_37_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit2_38_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit2_39_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit2_40_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit2_41_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit2_42_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit3_1_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit3_2_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit3_3_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit3_4_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit3_5_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit3_6_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit3_7_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit3_8_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit3_9_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit3_10_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit3_11_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit3_12_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit3_13_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit3_14_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit3_15_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit3_16_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit3_17_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit3_18_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit3_19_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit3_20_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit3_21_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit3_22_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit3_23_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit3_24_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit3_25_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit3_26_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit3_27_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit3_28_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit3_29_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit3_30_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit3_31_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit3_32_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit3_33_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit3_34_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit3_35_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit3_36_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit3_37_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit3_38_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit3_39_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit3_40_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit3_41_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit3_42_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit4_1_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit4_2_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit4_3_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit4_4_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit4_5_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit4_6_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit4_7_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit4_8_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit4_9_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit4_10_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit4_11_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit4_12_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit4_13_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit4_14_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit4_15_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit4_16_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit4_17_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit4_18_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit4_19_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit4_20_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit4_21_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit4_22_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit4_23_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit4_24_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit4_25_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit4_26_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit4_27_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit4_28_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit4_29_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit4_30_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit4_31_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit4_32_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit4_33_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit4_34_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit4_35_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit4_36_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit4_37_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit4_38_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit4_39_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit4_40_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit4_41_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
            'unit4_42_description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
        }
        labels = {
            'unit1_1': 'UNIT1',
            'unit1_2': 'UNIT2',
            'unit1_3': 'UNIT3',
            'unit1_4': 'UNIT4',
            'unit1_5': 'UNIT5',
            'unit1_6': 'UNIT6',
            'unit1_7': 'UNIT7',
            'unit1_8': 'UNIT8',
            'unit1_9': 'UNIT9',
            'unit1_10': 'UNIT10',
            'unit1_11': 'UNIT11',
            'unit1_12': 'UNIT12',
            'unit1_13': 'UNIT13',
            'unit1_14': 'UNIT14',
            'unit1_15': 'UNIT15',
            'unit1_16': 'UNIT16',
            'unit1_17': 'UNIT17',
            'unit1_18': 'UNIT18',
            'unit1_19': 'UNIT19',
            'unit1_20': 'UNIT20',
            'unit1_21': 'UNIT21',
            'unit1_22': 'UNIT22',
            'unit1_23': 'UNIT23',
            'unit1_24': 'UNIT24',
            'unit1_25': 'UNIT25',
            'unit1_26': 'UNIT26',
            'unit1_27': 'UNIT27',
            'unit1_28': 'UNIT28',
            'unit1_29': 'UNIT29',
            'unit1_30': 'UNIT30',
            'unit1_31': 'UNIT31',
            'unit1_32': 'UNIT32',
            'unit1_33': 'UNIT33',
            'unit1_34': 'UNIT34',
            'unit1_35': 'UNIT35',
            'unit1_36': 'UNIT36',
            'unit1_37': 'UNIT37',
            'unit1_38': 'UNIT38',
            'unit1_39': 'UNIT39',
            'unit1_40': 'UNIT40',
            'unit1_41': 'UNIT41',
            'unit1_42': 'UNIT42',
            'unit2_1': 'UNIT1',
            'unit2_2': 'UNIT2',
            'unit2_3': 'UNIT3',
            'unit2_4': 'UNIT4',
            'unit2_5': 'UNIT5',
            'unit2_6': 'UNIT6',
            'unit2_7': 'UNIT7',
            'unit2_8': 'UNIT8',
            'unit2_9': 'UNIT9',
            'unit2_10': 'UNIT10',
            'unit2_11': 'UNIT11',
            'unit2_12': 'UNIT12',
            'unit2_13': 'UNIT13',
            'unit2_14': 'UNIT14',
            'unit2_15': 'UNIT15',
            'unit2_16': 'UNIT16',
            'unit2_17': 'UNIT17',
            'unit2_18': 'UNIT18',
            'unit2_19': 'UNIT19',
            'unit2_20': 'UNIT20',
            'unit2_21': 'UNIT21',
            'unit2_22': 'UNIT22',
            'unit2_23': 'UNIT23',
            'unit2_24': 'UNIT24',
            'unit2_25': 'UNIT25',
            'unit2_26': 'UNIT26',
            'unit2_27': 'UNIT27',
            'unit2_28': 'UNIT28',
            'unit2_29': 'UNIT29',
            'unit2_30': 'UNIT30',
            'unit2_31': 'UNIT31',
            'unit2_32': 'UNIT32',
            'unit2_33': 'UNIT33',
            'unit2_34': 'UNIT34',
            'unit2_35': 'UNIT35',
            'unit2_36': 'UNIT36',
            'unit2_37': 'UNIT37',
            'unit2_38': 'UNIT38',
            'unit2_39': 'UNIT39',
            'unit2_40': 'UNIT40',
            'unit2_41': 'UNIT41',
            'unit2_42': 'UNIT42',
            'unit3_1': 'UNIT1',
            'unit3_2': 'UNIT2',
            'unit3_3': 'UNIT3',
            'unit3_4': 'UNIT4',
            'unit3_5': 'UNIT5',
            'unit3_6': 'UNIT6',
            'unit3_7': 'UNIT7',
            'unit3_8': 'UNIT8',
            'unit3_9': 'UNIT9',
            'unit3_10': 'UNIT10',
            'unit3_11': 'UNIT11',
            'unit3_12': 'UNIT12',
            'unit3_13': 'UNIT13',
            'unit3_14': 'UNIT14',
            'unit3_15': 'UNIT15',
            'unit3_16': 'UNIT16',
            'unit3_17': 'UNIT17',
            'unit3_18': 'UNIT18',
            'unit3_19': 'UNIT19',
            'unit3_20': 'UNIT20',
            'unit3_21': 'UNIT21',
            'unit3_22': 'UNIT22',
            'unit3_23': 'UNIT23',
            'unit3_24': 'UNIT24',
            'unit3_25': 'UNIT25',
            'unit3_26': 'UNIT26',
            'unit3_27': 'UNIT27',
            'unit3_28': 'UNIT28',
            'unit3_29': 'UNIT29',
            'unit3_30': 'UNIT30',
            'unit3_31': 'UNIT31',
            'unit3_32': 'UNIT32',
            'unit3_33': 'UNIT33',
            'unit3_34': 'UNIT34',
            'unit3_35': 'UNIT35',
            'unit3_36': 'UNIT36',
            'unit3_37': 'UNIT37',
            'unit3_38': 'UNIT38',
            'unit3_39': 'UNIT39',
            'unit3_40': 'UNIT40',
            'unit3_41': 'UNIT41',
            'unit3_42': 'UNIT42',
            'unit4_1': 'UNIT1',
            'unit4_2': 'UNIT2',
            'unit4_3': 'UNIT3',
            'unit4_4': 'UNIT4',
            'unit4_5': 'UNIT5',
            'unit4_6': 'UNIT6',
            'unit4_7': 'UNIT7',
            'unit4_8': 'UNIT8',
            'unit4_9': 'UNIT9',
            'unit4_10': 'UNIT10',
            'unit4_11': 'UNIT11',
            'unit4_12': 'UNIT12',
            'unit4_13': 'UNIT13',
            'unit4_14': 'UNIT14',
            'unit4_15': 'UNIT15',
            'unit4_16': 'UNIT16',
            'unit4_17': 'UNIT17',
            'unit4_18': 'UNIT18',
            'unit4_19': 'UNIT19',
            'unit4_20': 'UNIT20',
            'unit4_21': 'UNIT21',
            'unit4_22': 'UNIT22',
            'unit4_23': 'UNIT23',
            'unit4_24': 'UNIT24',
            'unit4_25': 'UNIT25',
            'unit4_26': 'UNIT26',
            'unit4_27': 'UNIT27',
            'unit4_28': 'UNIT28',
            'unit4_29': 'UNIT29',
            'unit4_30': 'UNIT30',
            'unit4_31': 'UNIT31',
            'unit4_32': 'UNIT32',
            'unit4_33': 'UNIT33',
            'unit4_34': 'UNIT34',
            'unit4_35': 'UNIT35',
            'unit4_36': 'UNIT36',
            'unit4_37': 'UNIT37',
            'unit4_38': 'UNIT38',
            'unit4_39': 'UNIT39',
            'unit4_40': 'UNIT40',
            'unit4_41': 'UNIT41',
            'unit4_42': 'UNIT42',
            'unit1_1_description': 'Rack_1_Unit_1_Description',
            'unit1_2_description': 'Rack_1_Unit_2_Description',
            'unit1_3_description': 'Rack_1_Unit_3_Description',
            'unit1_4_description': 'Rack_1_Unit_4_Description',
            'unit1_5_description': 'Rack_1_Unit_5_Description',
            'unit1_6_description': 'Rack_1_Unit_6_Description',
            'unit1_7_description': 'Rack_1_Unit_7_Description',
            'unit1_8_description': 'Rack_1_Unit_8_Description',
            'unit1_9_description': 'Rack_1_Unit_9_Description',
            'unit1_10_description': 'Rack_1_Unit_10_Description',
            'unit1_11_description': 'Rack_1_Unit_11_Description',
            'unit1_12_description': 'Rack_1_Unit_12_Description',
            'unit1_13_description': 'Rack_1_Unit_13_Description',
            'unit1_14_description': 'Rack_1_Unit_14_Description',
            'unit1_15_description': 'Rack_1_Unit_15_Description',
            'unit1_16_description': 'Rack_1_Unit_16_Description',
            'unit1_17_description': 'Rack_1_Unit_17_Description',
            'unit1_18_description': 'Rack_1_Unit_18_Description',
            'unit1_19_description': 'Rack_1_Unit_19_Description',
            'unit1_20_description': 'Rack_1_Unit_20_Description',
            'unit1_21_description': 'Rack_1_Unit_21_Description',
            'unit1_22_description': 'Rack_1_Unit_22_Description',
            'unit1_23_description': 'Rack_1_Unit_23_Description',
            'unit1_24_description': 'Rack_1_Unit_24_Description',
            'unit1_25_description': 'Rack_1_Unit_25_Description',
            'unit1_26_description': 'Rack_1_Unit_26_Description',
            'unit1_27_description': 'Rack_1_Unit_27_Description',
            'unit1_28_description': 'Rack_1_Unit_28_Description',
            'unit1_29_description': 'Rack_1_Unit_29_Description',
            'unit1_30_description': 'Rack_1_Unit_30_Description',
            'unit1_31_description': 'Rack_1_Unit_31_Description',
            'unit1_32_description': 'Rack_1_Unit_32_Description',
            'unit1_33_description': 'Rack_1_Unit_33_Description',
            'unit1_34_description': 'Rack_1_Unit_34_Description',
            'unit1_35_description': 'Rack_1_Unit_35_Description',
            'unit1_36_description': 'Rack_1_Unit_36_Description',
            'unit1_37_description': 'Rack_1_Unit_37_Description',
            'unit1_38_description': 'Rack_1_Unit_38_Description',
            'unit1_39_description': 'Rack_1_Unit_39_Description',
            'unit1_40_description': 'Rack_1_Unit_40_Description',
            'unit1_41_description': 'Rack_1_Unit_41_Description',
            'unit1_42_description': 'Rack_1_Unit_42_Description',
            'unit2_1_description': 'Rack_2_Unit_1_Description',
            'unit2_2_description': 'Rack_2_Unit_2_Description',
            'unit2_3_description': 'Rack_2_Unit_3_Description',
            'unit2_4_description': 'Rack_2_Unit_4_Description',
            'unit2_5_description': 'Rack_2_Unit_5_Description',
            'unit2_6_description': 'Rack_2_Unit_6_Description',
            'unit2_7_description': 'Rack_2_Unit_7_Description',
            'unit2_8_description': 'Rack_2_Unit_8_Description',
            'unit2_9_description': 'Rack_2_Unit_9_Description',
            'unit2_10_description': 'Rack_2_Unit_10_Description',
            'unit2_11_description': 'Rack_2_Unit_11_Description',
            'unit2_12_description': 'Rack_2_Unit_12_Description',
            'unit2_13_description': 'Rack_2_Unit_13_Description',
            'unit2_14_description': 'Rack_2_Unit_14_Description',
            'unit2_15_description': 'Rack_2_Unit_15_Description',
            'unit2_16_description': 'Rack_2_Unit_16_Description',
            'unit2_17_description': 'Rack_2_Unit_17_Description',
            'unit2_18_description': 'Rack_2_Unit_18_Description',
            'unit2_19_description': 'Rack_2_Unit_19_Description',
            'unit2_20_description': 'Rack_2_Unit_20_Description',
            'unit2_21_description': 'Rack_2_Unit_21_Description',
            'unit2_22_description': 'Rack_2_Unit_22_Description',
            'unit2_23_description': 'Rack_2_Unit_23_Description',
            'unit2_24_description': 'Rack_2_Unit_24_Description',
            'unit2_25_description': 'Rack_2_Unit_25_Description',
            'unit2_26_description': 'Rack_2_Unit_26_Description',
            'unit2_27_description': 'Rack_2_Unit_27_Description',
            'unit2_28_description': 'Rack_2_Unit_28_Description',
            'unit2_29_description': 'Rack_2_Unit_29_Description',
            'unit2_30_description': 'Rack_2_Unit_30_Description',
            'unit2_31_description': 'Rack_2_Unit_31_Description',
            'unit2_32_description': 'Rack_2_Unit_32_Description',
            'unit2_33_description': 'Rack_2_Unit_33_Description',
            'unit2_34_description': 'Rack_2_Unit_34_Description',
            'unit2_35_description': 'Rack_2_Unit_35_Description',
            'unit2_36_description': 'Rack_2_Unit_36_Description',
            'unit2_37_description': 'Rack_2_Unit_37_Description',
            'unit2_38_description': 'Rack_2_Unit_38_Description',
            'unit2_39_description': 'Rack_2_Unit_39_Description',
            'unit2_40_description': 'Rack_2_Unit_40_Description',
            'unit2_41_description': 'Rack_2_Unit_41_Description',
            'unit2_42_description': 'Rack_2_Unit_42_Description',
            'unit3_1_description': 'Rack_3_Unit_1_Description',
            'unit3_2_description': 'Rack_3_Unit_2_Description',
            'unit3_3_description': 'Rack_3_Unit_3_Description',
            'unit3_4_description': 'Rack_3_Unit_4_Description',
            'unit3_5_description': 'Rack_3_Unit_5_Description',
            'unit3_6_description': 'Rack_3_Unit_6_Description',
            'unit3_7_description': 'Rack_3_Unit_7_Description',
            'unit3_8_description': 'Rack_3_Unit_8_Description',
            'unit3_9_description': 'Rack_3_Unit_9_Description',
            'unit3_10_description': 'Rack_3_Unit_10_Description',
            'unit3_11_description': 'Rack_3_Unit_11_Description',
            'unit3_12_description': 'Rack_3_Unit_12_Description',
            'unit3_13_description': 'Rack_3_Unit_13_Description',
            'unit3_14_description': 'Rack_3_Unit_14_Description',
            'unit3_15_description': 'Rack_3_Unit_15_Description',
            'unit3_16_description': 'Rack_3_Unit_16_Description',
            'unit3_17_description': 'Rack_3_Unit_17_Description',
            'unit3_18_description': 'Rack_3_Unit_18_Description',
            'unit3_19_description': 'Rack_3_Unit_19_Description',
            'unit3_20_description': 'Rack_3_Unit_20_Description',
            'unit3_21_description': 'Rack_3_Unit_21_Description',
            'unit3_22_description': 'Rack_3_Unit_22_Description',
            'unit3_23_description': 'Rack_3_Unit_23_Description',
            'unit3_24_description': 'Rack_3_Unit_24_Description',
            'unit3_25_description': 'Rack_3_Unit_25_Description',
            'unit3_26_description': 'Rack_3_Unit_26_Description',
            'unit3_27_description': 'Rack_3_Unit_27_Description',
            'unit3_28_description': 'Rack_3_Unit_28_Description',
            'unit3_29_description': 'Rack_3_Unit_29_Description',
            'unit3_30_description': 'Rack_3_Unit_30_Description',
            'unit3_31_description': 'Rack_3_Unit_31_Description',
            'unit3_32_description': 'Rack_3_Unit_32_Description',
            'unit3_33_description': 'Rack_3_Unit_33_Description',
            'unit3_34_description': 'Rack_3_Unit_34_Description',
            'unit3_35_description': 'Rack_3_Unit_35_Description',
            'unit3_36_description': 'Rack_3_Unit_36_Description',
            'unit3_37_description': 'Rack_3_Unit_37_Description',
            'unit3_38_description': 'Rack_3_Unit_38_Description',
            'unit3_39_description': 'Rack_3_Unit_39_Description',
            'unit3_40_description': 'Rack_3_Unit_40_Description',
            'unit3_41_description': 'Rack_3_Unit_41_Description',
            'unit3_42_description': 'Rack_3_Unit_42_Description',
            'unit4_1_description': 'Rack_4_Unit_1_Description',
            'unit4_2_description': 'Rack_4_Unit_2_Description',
            'unit4_3_description': 'Rack_4_Unit_3_Description',
            'unit4_4_description': 'Rack_4_Unit_4_Description',
            'unit4_5_description': 'Rack_4_Unit_5_Description',
            'unit4_6_description': 'Rack_4_Unit_6_Description',
            'unit4_7_description': 'Rack_4_Unit_7_Description',
            'unit4_8_description': 'Rack_4_Unit_8_Description',
            'unit4_9_description': 'Rack_4_Unit_9_Description',
            'unit4_10_description': 'Rack_4_Unit_10_Description',
            'unit4_11_description': 'Rack_4_Unit_11_Description',
            'unit4_12_description': 'Rack_4_Unit_12_Description',
            'unit4_13_description': 'Rack_4_Unit_13_Description',
            'unit4_14_description': 'Rack_4_Unit_14_Description',
            'unit4_15_description': 'Rack_4_Unit_15_Description',
            'unit4_16_description': 'Rack_4_Unit_16_Description',
            'unit4_17_description': 'Rack_4_Unit_17_Description',
            'unit4_18_description': 'Rack_4_Unit_18_Description',
            'unit4_19_description': 'Rack_4_Unit_19_Description',
            'unit4_20_description': 'Rack_4_Unit_20_Description',
            'unit4_21_description': 'Rack_4_Unit_21_Description',
            'unit4_22_description': 'Rack_4_Unit_22_Description',
            'unit4_23_description': 'Rack_4_Unit_23_Description',
            'unit4_24_description': 'Rack_4_Unit_24_Description',
            'unit4_25_description': 'Rack_4_Unit_25_Description',
            'unit4_26_description': 'Rack_4_Unit_26_Description',
            'unit4_27_description': 'Rack_4_Unit_27_Description',
            'unit4_28_description': 'Rack_4_Unit_28_Description',
            'unit4_29_description': 'Rack_4_Unit_29_Description',
            'unit4_30_description': 'Rack_4_Unit_30_Description',
            'unit4_31_description': 'Rack_4_Unit_31_Description',
            'unit4_32_description': 'Rack_4_Unit_32_Description',
            'unit4_33_description': 'Rack_4_Unit_33_Description',
            'unit4_34_description': 'Rack_4_Unit_34_Description',
            'unit4_35_description': 'Rack_4_Unit_35_Description',
            'unit4_36_description': 'Rack_4_Unit_36_Description',
            'unit4_37_description': 'Rack_4_Unit_37_Description',
            'unit4_38_description': 'Rack_4_Unit_38_Description',
            'unit4_39_description': 'Rack_4_Unit_39_Description',
            'unit4_40_description': 'Rack_4_Unit_40_Description',
            'unit4_41_description': 'Rack_4_Unit_41_Description',
            'unit4_42_description': 'Rack_4_Unit_42_Description',
        }
