# Generated by Django 3.1.4 on 2021-01-04 06:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='installbase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('customer', models.TextField()),
                ('installedat', models.TextField()),
                ('project_name', models.TextField()),
                ('model', models.TextField()),
                ('osversion', models.TextField()),
                ('serialnumber', models.TextField()),
                ('hostname', models.TextField()),
                ('ipslist', models.TextField()),
                ('shelfmodel', models.TextField()),
                ('storage_name', models.TextField()),
                ('disk', models.TextField()),
                ('diskmodel', models.TextField()),
                ('shelfemptyslot', models.TextField()),
                ('slotinfo', models.TextField()),
                ('installedate', models.DateField()),
                ('warrantydate', models.DateField()),
                ('engineername', models.TextField()),
                ('controllereoa', models.DateField()),
                ('controllereos', models.DateField()),
                ('addlist', models.TextField()),
                ('deleted', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_storage', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
