# Generated by Django 3.1.5 on 2021-03-10 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installbase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='installbase',
            name='warrantytype',
            field=models.TextField(default='무상'),
        ),
    ]
