# Generated by Django 3.1.4 on 2021-01-06 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('installbase', '0002_auto_20210106_1510'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='installbase',
            options={'ordering': ['-installedate']},
        ),
        migrations.RemoveField(
            model_name='installbase',
            name='author',
        ),
    ]
