# Generated by Django 3.1.4 on 2021-01-07 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installbase', '0004_auto_20210107_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='installbase',
            name='production',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='installbase',
            name='controllereoa',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='installbase',
            name='controllereos',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='installbase',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
