# Generated by Django 3.1.4 on 2021-01-07 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installbase', '0005_auto_20210107_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installbase',
            name='controllereoa',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='installbase',
            name='controllereos',
            field=models.DateField(blank=True, null=True),
        ),
    ]
