# Generated by Django 3.1.4 on 2021-01-11 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installbase', '0006_auto_20210107_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='installbase',
            name='licensed',
            field=models.TextField(default='CIFS', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='installbase',
            name='production',
            field=models.BooleanField(default=True),
        ),
    ]
