# Generated by Django 3.1.4 on 2021-01-11 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installbase', '0009_auto_20210111_1728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='installbase',
            name='licensed',
        ),
        migrations.AddField(
            model_name='installbase',
            name='licensed',
            field=models.CharField(default='CIFS', max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='licenses',
        ),
    ]
