# Generated by Django 3.1.4 on 2021-01-11 09:01

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('installbase', '0011_auto_20210111_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installbase',
            name='licensed',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('CIFS', 'CIFS'), ('NFS', 'NFS')], max_length=8),
        ),
    ]
