# Generated by Django 3.1.4 on 2021-01-12 01:54

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('installbase', '0012_auto_20210111_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='installbase',
            name='sanswitch',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='installbase',
            name='sanswitchhostname',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='installbase',
            name='sanswitchipaddress',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='installbase',
            name='sanswitchmodel',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='installbase',
            name='sanswitchport',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='installbase',
            name='sanswitchportlicense',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='installbase',
            name='sanswitchserial',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='installbase',
            name='licensed',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('CIFS', 'CIFS'), ('NFS', 'NFS'), ('FCP', 'FCP'), ('iSCSI', 'iSCSI'), ('FlexClone', 'FlexClone'), ('SnapMirror', 'SnapMirror'), ('SnapRestore', 'SnapRestore')], max_length=51),
        ),
    ]
