# Generated by Django 3.1.5 on 2021-01-13 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installbase', '0013_auto_20210112_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installbase',
            name='sanswitch',
            field=models.CharField(max_length=10),
        ),
    ]
