# Generated by Django 3.1.5 on 2021-01-13 07:51

from django.db import migrations, models
import installbase.models


class Migration(migrations.Migration):

    dependencies = [
        ('installbase', '0014_auto_20210113_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='installbase',
            name='filename',
            field=models.CharField(max_length=64, null=True, verbose_name='첨부파일명'),
        ),
        migrations.AddField(
            model_name='installbase',
            name='upload_files',
            field=models.FileField(blank=True, null=True, upload_to=installbase.models.get_file_path, verbose_name='파일'),
        ),
    ]
